In [1]:
a = 10

In [2]:
print(a)

10


In [3]:
a += 5
a

15

In [4]:
import torch

In [5]:
a = torch.tensor([2. ,3.], requires_grad=True)
b = torch.tensor([6. ,4.], requires_grad=True)

f = 3 * a**3 - b**3

$$
f = 3a^3 - b^2
$$

$$
\frac{\partial f}{\partial a} = 9a^2
$$

$$
\frac{\partial f}{\partial b} = -2b
$$

In [6]:
f

tensor([-192.,   17.], grad_fn=<SubBackward0>)

In [7]:
f.backward(gradient=torch.tensor([1, 1]))

In [8]:
print(a.grad)

tensor([36., 81.])


In [9]:
9 * a**2

tensor([36., 81.], grad_fn=<MulBackward0>)

In [10]:
print(b.grad)

tensor([-108.,  -48.])


In [11]:
-2 * b

tensor([-12.,  -8.], grad_fn=<MulBackward0>)